config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :appointments
  resources :trucks
  resources :users
  root to: 'trucks#index'

  resources :trucks do
    member do
      put "like" => "trucks#like"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :truck
end

app/models/score.rb
class Score < ApplicationRecord
    has_many :users
    has_many :trucks

end

app/models/truck.rb
class Truck < ApplicationRecord
  belongs_to :user
  belongs_to :type_truck
  has_many :appointments, :dependent => :destroy
  has_one_attached :picture

  acts_as_votable

end
 

app/models/type_truck.rb
class TypeTruck < ApplicationRecord
    has_many :trucks, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :trucks, dependent: :destroy


    validates :name, presence: true

    acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.user_id = current.user.id

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:appointment_date, :status, :user_id, :truck_id)
    end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :set_truck, only: %i[ show edit update destroy ]

  respond_to :js, :html, :json

  # GET /trucks or /trucks.json
  def index
    @trucks = Truck.all
    if(params[:search] && !params[:search].empty?)
    else
      if signed_in?
      @trucks = Truck.where("description LIKE ?", "%#{params[:search]}%").order(created_at: :desc)
    end
  end

    
  end

  # GET /trucks/1 or /trucks/1.json
  def show
  end

  # GET /trucks/new
  def new
    @truck = Truck.new
  end

  # GET /trucks/1/edit
  def edit
  end

  def like
    @truck = Truck.find(params[:id])
    puts "camion:#{@truck.inspect}}"
    if params[:format] == 'like'
      @truck.liked_by current_user
    elsif params[:format] == 'unlike'
      @truck.unliked_by current_user
    end
    redirect_to root_path
  end

  # POST /trucks or /trucks.json
  def create
    @truck = Truck.new(truck_params.except(:type_truck))
    @truck.type_truck = TypeTruck.create(name: params["truck"]["type_truck"])
    @truck.user_id = current_user.id

    respond_to do |format|
      if @truck.save
        format.html { redirect_to @truck, notice: "Truck was successfully created." }
        format.json { render :show, status: :created, location: @truck }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trucks/1 or /trucks/1.json
  def update
    @truck.user_id = current_user.id
    respond_to do |format|
      if @truck.update(truck_params.except(:type_truck))
        format.html { redirect_to @truck, notice: "Truck was successfully updated." }
        format.json { render :show, status: :ok, location: @truck }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trucks/1 or /trucks/1.json
  def destroy
    @truck.destroy
    respond_to do |format|
      format.html { redirect_to trucks_url, notice: "Truck was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truck
      @truck = Truck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def truck_params
      params.require(:truck).permit(:picture, :description, :tonnage, :rate, :region, :commune, :type_truck)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :surname, :email, :phone, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :appointment_date %>
    <%= form.date_select :appointment_date %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :truck_id %>
    <%= form.text_field :truck_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Appointment date</th>
      <th>Status</th>
      <th>User</th>
      <th>Truck</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.appointment_date %></td>
        <td><%= appointment.status %></td>
        <td><%= appointment.user %></td>
        <td><%= appointment.truck %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appointment date:</strong>
  <%= @appointment.appointment_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @appointment.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @appointment.user %>
</p>

<p>
  <strong>Truck:</strong>
  <%= @appointment.truck %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Itruckers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body>


  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <%= link_to "iTruckers", root_path, :class => 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Find it", trucks_url, :class => 'nav-link' %>
        </li>

        <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to "My User", users_url, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Create Truck", new_truck_url, :class => 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to "My Appointment", appointments_url, :class => 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'nav-link' %>
        </li>

        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_url, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_url, :class => 'nav-link' %>
        </li>
        <% end %>

      </ul>
    </div>
  </nav>
    <div class="container margin_top">
<%
=begin%>
 
      <div class="container">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
      </div> 
<%
=end%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/trucks/_form.html.erb
<%= form_with(model: truck, local: true) do |form| %>
  <% if truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(truck.errors.count, "error") %> prohibited this truck from being saved:</h2>

      <ul>
      <% truck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field ">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :type_truck %>
    <%= form.select :type_truck, ['Camión Rígido', 'Camión Articulado', 'Camión de Plataforma Abierta', 'Camión con Lona', 'Camión Frigorífico', 'Camión Cisterna', 'Camión Cerrado', 'Camión Porta-Autos', 'Camión Jaula', 'Camión Contenedor'], :class => "form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :tonnage %>
    <%= form.text_field :tonnage, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :region %>
    <%= form.text_field :region, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :commune %>
    <%= form.text_field :commune, :class => "form-control" %>
  </div>


  <div class="field form-group">
    <%= form.label :rate %>
    <%= form.text_field :rate, :class => "form-control" %>
  </div>


  <div class="actions mt-3">
    <%= form.submit "Crear", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/trucks/edit.html.erb
<h1>Editing Truck</h1>

<%= render 'form', truck: @truck %>

<%= link_to 'Show', @truck %> |
<%= link_to 'Back', trucks_path %>

app/views/trucks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trucks</h1>

<div class="w-100 mt-2">
  <%= form_tag(root_path, method: :get) do %>
    <div class="form-group">
      <%= submit_tag("buscar", :class => "ml-2 btn-primary text-white float-right") %>
      <%= text_field_tag(:search, params[:search], :class => "w-50 float-right form-control d-inline") %>
    </div>
  <% end %>
</div>

<table class="table table-borderless">
  <thead>
    <tr>
      <th>Image</th>
      <th class="descriptionTruck">Description</th>
      <th>Type</th>
      <th>Tonnage</th>
      <th>Region</th>
      <th>Commune</th>
      <th>Rate</th>
      <% if current_user %>      
        <th>User</th>
        <th>Score</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trucks.each do |truck| %>
      <tr>
        <td><%= image_tag truck.picture.variant(resize: "100x100") %></td>
        <td><%= truck.description %></td>
        <td><%= truck.type_truck.name %></td>
        <td><%= truck.tonnage %></td>
        <td><%= truck.region %></td>
        <td><%= truck.commune %></td>
        <td><%= truck.rate %></td>    

        <% if user_signed_in? %>    
          <td><%= truck.user.name %></td>
          <td>
          <span class="parent-likes">
              <span class = "like_count" <%= truck.id %> >
                <%= truck.get_likes.size %> &#128591 
              </span>
                <a>
                  <% if current_user.liked? truck %>
                      <div> <%= link_to like_truck_path(truck, 'unlike'), class: "preached-btn", method: :put, remote: :true do %> Preached </div>
                    <% end %>
                    <% else %>
                        <div> <%= link_to like_truck_path(truck, 'like'), class:"preach-btn", method: :put, remote: :true do %> Preach </div>
                    <% end %>
                  <% end %>
                <a>
            </span>

        <% end %>

          <% if user_signed_in? && truck.user.id == current_user.id %>
          </td>
          <td><%= link_to 'Show', truck %></td>
          <td><%= link_to 'Edit', edit_truck_path(truck) %></td>
          <td><%= link_to 'Destroy', truck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in?  %>
  <%= link_to 'New Truck', new_truck_path %>
<% end %>

app/views/trucks/like.js.erb
$('.preached-btn').on('ajax:success', function(){
    $(this).parent().parent().find('.like_count').html('<%= @truck.get_likes.size %> &#128591';
    $(this).closest('.preached-btn').html('Preach');
});

$('.preach-btn').on('ajax:success', function(){
    $(this).parent().parent().find('.like_count').html('<%= @truck.get_likes.size %> &128591');
    $(this).closest('.preach-btn').html('Preached');
    });

app/views/trucks/new.html.erb
<h1 class="mb-3 text-center">Publish your new truck</h1>

<%= render 'form', truck: @truck %>

<%= link_to 'Back', trucks_path, :class => "mt-2"%>

app/views/trucks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @truck.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @truck.description %>
</p>

<p>
  <strong>Tonnage:</strong>
  <%= @truck.tonnage %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @truck.rate %>
</p>

<p>
  <strong>Region:</strong>
  <%= @truck.region %>
</p>

<p>
  <strong>Commune:</strong>
  <%= @truck.commune %>
</p>

<p>
  <strong>User:</strong>
  <%= @truck.user %>
</p>

<p>
  <strong>Type truck:</strong>
  <%= @truck.type_truck %>
</p>

<%= link_to 'Edit', edit_truck_path(@truck) %> |
<%= link_to 'Back', trucks_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :surname %>
    <%= form.text_field :surname, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.number_field :phone, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :role %>
    <%= form.select :role, ['Owner', 'Client'], :class => "form-control"%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Surname</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr scope="row">
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @user.surname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Score:</strong>
  <%= @user.score %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>